### ISSUE TITLE
The engine can only predict no any class

### ISSUE THREAD

**Issue by JosephKL-Chan** [marcoslucianops/DeepStream-Yolo-Pose#11]
Our organization had the issue that we use Yolov8n model, we use deepstream-yolo change it to onnx format. and we follow the https://github.com/marcoslucianops/DeepStream-Yolo-Pose/blob/master/docs/YOLOv8_Pose.md YOLOv8-Pose usage step to setup the deepstream. But only one class can detected.
Our process was:
1. python3 export_yoloV8_pose.py -w yolov8s-pose.pt --dynamic --simplify 
2. Copy onnx to deepstream folder.
4. Use onnx change engine
./trtexec --onnx=yolov8npose.onnx  --saveEngine=yolov8npose.engine
3. Compile nvdsinfer_custom_impl_Yolo plugin
4. Edit the config_infer_primary_yoloV8_pose.txt
(...
onnx-file=yolov8npose.onnx
model-engine-file=yolov8npose.engine
network-mode=0
num-detected-classes=3
network-type=3
cluster-mode=4
...
parse-bbox-func-name=NvDsInferParseYoloPose)
...
[class-attrs-all]
pre-cluster-threshold=0.25
topk=300
5. Edit label.txt
6. Run RTSP Programe

**Comment by marcoslucianops** [comment]
Please try with the updated files.
