### ISSUE TITLE
Unable to convert function return value to a Python type! The signature was

### ISSUE THREAD

**Issue by Mangesh1996** [marcoslucianops/DeepStream-Yolo-Pose#2]
ile "deepstream.py", line 88, in parse_pose_from_meta
    num_joints = int(obj_meta.mask_params.size / (sizeof(c_float) * 3))
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: pyds.NvDsObjectMeta) -> _NvOSD_MaskParams

**Comment by willosonico** [comment]
i got this error too

in parse_pose_from_meta
    num_joints = int(obj_meta.mask_params.size / (sizeof(c_float) * 3))
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: pyds.NvDsObjectMeta) -> _NvOSD_MaskParams

with deepstream 6.1

**Comment by willosonico** [comment]
solved by installing pyds 1.1.8, my version was 1.1.3
