### ISSUE TITLE
Receiving an error while running demo on Jetson

### ISSUE THREAD

**Issue by Prasantkumar987** [marcoslucianops/DeepStream-Yolo-Pose#3]
Traceback (most recent call last):
  File "deepstream.py", line 178, in tracker_src_pad_buffer_probe
    parse_pose_from_meta(frame_meta, obj_meta)
  File "deepstream.py", line 129, in parse_pose_from_meta
    x1 = int((data[(skeleton[i][0] - 1) * 3 + 0] - pad_x) / gain)
IndexError: index 45 is out of bounds for axis 0 with size 0

**Comment by marcoslucianops** [comment]
Which model are you using?

**Comment by Prasantkumar987** [comment]
Yolov8

**Comment by marcoslucianops** [comment]
Please send me the output from the terminal from the beginning to the error.

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo-Pose/blob/master/docs/YOLOv8_Pose.md

**Comment by Prasantkumar987** [comment]
For Current Config of DeepStream, Do I have to change size and shape of input image?. I think there the problem is occuring.

**Comment by marcoslucianops** [comment]
You need to use my `export_yoloV8_pose.py` file to export the model. Please follow the link I sent.

**Comment by Prasantkumar987** [comment]
Thank you @marcoslucianops  I'll follow  `export_yolov8_pose.py` to export the model. 
Once I am able to run it, I'll close this Issue.

**Comment by Prasantkumar987** [comment]
@marcoslucianops Just an update, It started running after exporting onnx file using `export_yolov8_pose.py` .
Made it running at 19 fps 👍
